[package]
name = "CoinMint"
version = "0.0.0"

[addresses]
admin = "014f46dcfb789acaa1fafbba707da3e719cce8ea1c9790e6d398a4e9b2a283ba"
source = "014f46dcfb789acaa1fafbba707da3e719cce8ea1c9790e6d398a4e9b2a283ba"
# place holder for dev to comment
coin_mint = "014f46dcfb789acaa1fafbba707da3e719cce8ea1c9790e6d398a4e9b2a283ba"

[dependencies]
AptosFramework = { local = "/home/titouanmarchal/ThounyBreasty/Playground/Aptos/aptos-core/aptos-move/framework/aptos-framework" }
# AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'devnet', subdir = 'aptos-move/framework/aptos-framework'}